dist: xenial
language: generic
services:
  - postgresql
addons:
  postgresql: '10'
before_install:
  - pyenv local 3.7.1
install:
  - PYTHON=python make
before_script:
  - createdb newdle_tests
  - source .venv/bin/activate
script:
  - make lint
  - make test
notifications:
  email: false
