"""Add creator email column to db model

Revision ID: aa8c14c9e867
Revises: c161fdcfab19
Create Date: 2020-09-14 16:40:23.418303
"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'aa8c14c9e867'
down_revision = 'c161fdcfab19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newdles', sa.Column('creator_email', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newdles', 'creator_email')
    # ### end Alembic commands ###
