theme: jekyll-theme-cayman
title: Newdle Project
github_username: indico
description: > # this means to ignore newlines until "baseurl:"
 Newdle Project Official site
#baseurl: "/newdle/" # Uncomment this line once it is in indico's repo
#url: "https://getindico.io" # Uncomment this line once it is in indico's repo
