theme: jekyll-theme-cayman
title: Newdle Project
github_username: newdle
description: > # this means to ignore newlines until "baseurl:"
 Newdle Project Official site
baseurl: "/newdle" # the subpath of your site, e.g. /blog/
url: "https://getindico.io" # the base hostname & protocol for your site
